name: 'Ready for Review'
description: 'An action for automatically label swapping for draft pull requests'
author: 'Jinma Yamashita'
inputs: 
  in-progress-label:
    description: 'In progress labels'
    required: true
    default: 'In progress'
  ready-for-review-label:
    description: 'Ready for review labels'
    required: true
    default: 'Ready for review'
  repo-token:
    required: true
    description: 'Github token'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'toggle-left'
  color: 'purple'
